/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardApiRouteImport } from './routes/_authenticated/dashboard.api'
import { Route as AuthenticatedDashboardFilterRouteImport } from './routes/_authenticated/dashboard.filter'
import { Route as AuthenticatedDashboardImportRouteImport } from './routes/_authenticated/dashboard.import'
import { Route as AuthenticatedDashboardKeysRouteImport } from './routes/_authenticated/dashboard.keys'
import { Route as AuthenticatedDashboardLeadsRouteImport } from './routes/_authenticated/dashboard.leads'
import { Route as AuthenticatedDashboardLogsRouteImport } from './routes/_authenticated/dashboard.logs'
import { Route as ApiPublicV1CountRouteImport } from './routes/api/public/v1/count'
import { Route as ApiPublicV1CountriesRouteImport } from './routes/api/public/v1/countries'
import { Route as ApiPublicV1LeadsRouteImport } from './routes/api/public/v1/leads'
import { Route as ApiPublicV1SchemaRouteImport } from './routes/api/public/v1/schema'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardApiRoute =
  AuthenticatedDashboardApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFilterRoute =
  AuthenticatedDashboardFilterRouteImport.update({
    id: '/filter',
    path: '/filter',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardImportRoute =
  AuthenticatedDashboardImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKeysRoute =
  AuthenticatedDashboardKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLeadsRoute =
  AuthenticatedDashboardLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLogsRoute =
  AuthenticatedDashboardLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicV1CountRoute = ApiPublicV1CountRouteImport.update({
  id: '/api/public/v1/count',
  path: '/api/public/v1/count',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CountriesRoute = ApiPublicV1CountriesRouteImport.update({
  id: '/api/public/v1/countries',
  path: '/api/public/v1/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1LeadsRoute = ApiPublicV1LeadsRouteImport.update({
  id: '/api/public/v1/leads',
  path: '/api/public/v1/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SchemaRoute = ApiPublicV1SchemaRouteImport.update({
  id: '/api/public/v1/schema',
  path: '/api/public/v1/schema',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/api': typeof AuthenticatedDashboardApiRoute
  '/dashboard/filter': typeof AuthenticatedDashboardFilterRoute
  '/dashboard/import': typeof AuthenticatedDashboardImportRoute
  '/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/v1/count': typeof ApiPublicV1CountRoute
  '/api/public/v1/countries': typeof ApiPublicV1CountriesRoute
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/api/public/v1/schema': typeof ApiPublicV1SchemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/api': typeof AuthenticatedDashboardApiRoute
  '/dashboard/filter': typeof AuthenticatedDashboardFilterRoute
  '/dashboard/import': typeof AuthenticatedDashboardImportRoute
  '/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/v1/count': typeof ApiPublicV1CountRoute
  '/api/public/v1/countries': typeof ApiPublicV1CountriesRoute
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/api/public/v1/schema': typeof ApiPublicV1SchemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/api': typeof AuthenticatedDashboardApiRoute
  '/_authenticated/dashboard/filter': typeof AuthenticatedDashboardFilterRoute
  '/_authenticated/dashboard/import': typeof AuthenticatedDashboardImportRoute
  '/_authenticated/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/_authenticated/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/_authenticated/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/v1/count': typeof ApiPublicV1CountRoute
  '/api/public/v1/countries': typeof ApiPublicV1CountriesRoute
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/api/public/v1/schema': typeof ApiPublicV1SchemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/api'
    | '/dashboard/filter'
    | '/dashboard/import'
    | '/dashboard/keys'
    | '/dashboard/leads'
    | '/dashboard/logs'
    | '/dashboard/'
    | '/api/public/v1/count'
    | '/api/public/v1/countries'
    | '/api/public/v1/leads'
    | '/api/public/v1/schema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/api'
    | '/dashboard/filter'
    | '/dashboard/import'
    | '/dashboard/keys'
    | '/dashboard/leads'
    | '/dashboard/logs'
    | '/dashboard'
    | '/api/public/v1/count'
    | '/api/public/v1/countries'
    | '/api/public/v1/leads'
    | '/api/public/v1/schema'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/api'
    | '/_authenticated/dashboard/filter'
    | '/_authenticated/dashboard/import'
    | '/_authenticated/dashboard/keys'
    | '/_authenticated/dashboard/leads'
    | '/_authenticated/dashboard/logs'
    | '/_authenticated/dashboard/'
    | '/api/public/v1/count'
    | '/api/public/v1/countries'
    | '/api/public/v1/leads'
    | '/api/public/v1/schema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicV1CountRoute: typeof ApiPublicV1CountRoute
  ApiPublicV1CountriesRoute: typeof ApiPublicV1CountriesRoute
  ApiPublicV1LeadsRoute: typeof ApiPublicV1LeadsRoute
  ApiPublicV1SchemaRoute: typeof ApiPublicV1SchemaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/api': {
      id: '/_authenticated/dashboard/api'
      path: '/api'
      fullPath: '/dashboard/api'
      preLoaderRoute: typeof AuthenticatedDashboardApiRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/filter': {
      id: '/_authenticated/dashboard/filter'
      path: '/filter'
      fullPath: '/dashboard/filter'
      preLoaderRoute: typeof AuthenticatedDashboardFilterRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/import': {
      id: '/_authenticated/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof AuthenticatedDashboardImportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/keys': {
      id: '/_authenticated/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof AuthenticatedDashboardKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/leads': {
      id: '/_authenticated/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AuthenticatedDashboardLeadsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/logs': {
      id: '/_authenticated/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof AuthenticatedDashboardLogsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/v1/count': {
      id: '/api/public/v1/count'
      path: '/api/public/v1/count'
      fullPath: '/api/public/v1/count'
      preLoaderRoute: typeof ApiPublicV1CountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/countries': {
      id: '/api/public/v1/countries'
      path: '/api/public/v1/countries'
      fullPath: '/api/public/v1/countries'
      preLoaderRoute: typeof ApiPublicV1CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/leads': {
      id: '/api/public/v1/leads'
      path: '/api/public/v1/leads'
      fullPath: '/api/public/v1/leads'
      preLoaderRoute: typeof ApiPublicV1LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/schema': {
      id: '/api/public/v1/schema'
      path: '/api/public/v1/schema'
      fullPath: '/api/public/v1/schema'
      preLoaderRoute: typeof ApiPublicV1SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardApiRoute: typeof AuthenticatedDashboardApiRoute
  AuthenticatedDashboardFilterRoute: typeof AuthenticatedDashboardFilterRoute
  AuthenticatedDashboardImportRoute: typeof AuthenticatedDashboardImportRoute
  AuthenticatedDashboardKeysRoute: typeof AuthenticatedDashboardKeysRoute
  AuthenticatedDashboardLeadsRoute: typeof AuthenticatedDashboardLeadsRoute
  AuthenticatedDashboardLogsRoute: typeof AuthenticatedDashboardLogsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardApiRoute: AuthenticatedDashboardApiRoute,
    AuthenticatedDashboardFilterRoute: AuthenticatedDashboardFilterRoute,
    AuthenticatedDashboardImportRoute: AuthenticatedDashboardImportRoute,
    AuthenticatedDashboardKeysRoute: AuthenticatedDashboardKeysRoute,
    AuthenticatedDashboardLeadsRoute: AuthenticatedDashboardLeadsRoute,
    AuthenticatedDashboardLogsRoute: AuthenticatedDashboardLogsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicV1CountRoute: ApiPublicV1CountRoute,
  ApiPublicV1CountriesRoute: ApiPublicV1CountriesRoute,
  ApiPublicV1LeadsRoute: ApiPublicV1LeadsRoute,
  ApiPublicV1SchemaRoute: ApiPublicV1SchemaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
