ALTER TABLE public.countries ADD COLUMN IF NOT EXISTS name_ar text;
ALTER TABLE public.countries ADD COLUMN IF NOT EXISTS dial_code text;

INSERT INTO public.countries (code, name, name_ar, dial_code) VALUES
('AW','Aruba','أروبا','297'),
('AF','Afghanistan','أفغانستان','93'),
('AO','Angola','جمهورية أنغولا','244'),
('AI','Anguilla','أنغويلا','1264'),
('AX','Åland Islands','جزر أولاند','35818'),
('AL','Albania','ألبانيا','355'),
('AD','Andorra','أندورا','376'),
('AE','United Arab Emirates','الإمارات','971'),
('AR','Argentina','الأرجنتين','54'),
('AM','Armenia','أرمينيا','374'),
('AS','American Samoa','ساموا الأمريكية','1684'),
('AQ','Antarctica','أنتارتيكا',NULL),
('TF','French Southern and Antarctic Lands','أراض فرنسية جنوبية وأنتارتيكية','262'),
('AG','Antigua and Barbuda','أنتيغوا وباربودا','1268'),
('AU','Australia','أستراليا','61'),
('AT','Austria','النمسا','43'),
('AZ','Azerbaijan','أذربيجان','994'),
('BI','Burundi','بوروندي','257'),
('BE','Belgium','بلجيكا','32'),
('BJ','Benin','بنين','229'),
('BF','Burkina Faso','بوركينا فاسو','226'),
('BD','Bangladesh','بنغلاديش','880'),
('BG','Bulgaria','بلغاريا','359'),
('BH','Bahrain','البحرين','973'),
('BS','Bahamas','البهاما','1242'),
('BA','Bosnia and Herzegovina','البوسنة والهرسك','387'),
('BL','Saint Barthélemy','سان بارتليمي','590'),
('SH','Saint Helena, Ascension and Tristan da Cunha','سانت هيلينا وأسينشين وتريستان دا كونا','2'),
('BY','Belarus','بيلاروسيا','375'),
('BZ','Belize','بليز','501'),
('BM','Bermuda','برمودا','1441'),
('BO','Bolivia','بوليفيا','591'),
('BQ','Caribbean Netherlands','الجزر الكاريبية الهولندية','599'),
('BR','Brazil','البرازيل','55'),
('BB','Barbados','باربادوس','1246'),
('BN','Brunei','بروناي','673'),
('BT','Bhutan','بوتان','975'),
('BV','Bouvet Island','جزر بوفيه','47'),
('BW','Botswana','بوتسوانا','267'),
('CF','Central African Republic','جمهورية أفريقيا الوسطى','236'),
('CA','Canada','كندا','1'),
('CC','Cocos (Keeling) Islands','جزر كوكوس','61'),
('CH','Switzerland','سويسرا','41'),
('CL','Chile','تشيلي','56'),
('CN','China','الصين','86'),
('CI','Ivory Coast','ساحل العاج','225'),
('CM','Cameroon','الكاميرون','237'),
('CD','DR Congo','الكونغو','243'),
('CG','Republic of the Congo','جمهورية الكونغو','242'),
('CK','Cook Islands','جزر كوك','682'),
('CO','Colombia','كولومبيا','57'),
('KM','Comoros','جزر القمر','269'),
('CV','Cape Verde','كابو فيردي','238'),
('CR','Costa Rica','كوستاريكا','506'),
('CU','Cuba','كوبا','53'),
('CW','Curaçao','كوراساو','599'),
('CX','Christmas Island','جزيرة كريسماس','61'),
('KY','Cayman Islands','جزر كايمان','1345'),
('CY','Cyprus','قبرص','357'),
('CZ','Czechia','التشيك','420'),
('DE','Germany','ألمانيا','49'),
('DJ','Djibouti','جيبوتي','253'),
('DM','Dominica','دومينيكا','1767'),
('DK','Denmark','الدنمارك','45'),
('DO','Dominican Republic','جمهورية الدومينيكان','1'),
('DZ','Algeria','الجزائر','213'),
('EC','Ecuador','الإكوادور','593'),
('EG','Egypt','مصر','20'),
('ER','Eritrea','إريتريا','291'),
('EH','Western Sahara','الصحراء الغربية','2'),
('ES','Spain','إسبانيا','34'),
('EE','Estonia','إستونيا','372'),
('ET','Ethiopia','إثيوبيا','251'),
('FI','Finland','فنلندا','358'),
('FJ','Fiji','فيجي','679'),
('FK','Falkland Islands','جزر فوكلاند','500'),
('FR','France','فرنسا','33'),
('FO','Faroe Islands','جزر فارو','298'),
('FM','Micronesia','ميكرونيسيا','691'),
('GA','Gabon','الغابون','241'),
('GB','United Kingdom','المملكة المتحدة','44'),
('GE','Georgia','جورجيا','995'),
('GG','Guernsey','غيرنزي','44'),
('GH','Ghana','غانا','233'),
('GI','Gibraltar','جبل طارق','350'),
('GN','Guinea','غينيا','224'),
('GP','Guadeloupe','غوادلوب','590'),
('GM','Gambia','غامبيا','220'),
('GW','Guinea-Bissau','غينيا بيساو','245'),
('GQ','Equatorial Guinea','غينيا الاستوائية','240'),
('GR','Greece','اليونان','30'),
('GD','Grenada','غرينادا','1473'),
('GL','Greenland','جرينلاند','299'),
('GT','Guatemala','غواتيمالا','502'),
('GF','French Guiana','غويانا','594'),
('GU','Guam','غوام','1671'),
('GY','Guyana','غيانا','592'),
('HK','Hong Kong','هونغ كونغ','852'),
('HM','Heard Island and McDonald Islands','جزيرة هيرد وجزر ماكدونالد',NULL),
('HN','Honduras','هندوراس','504'),
('HR','Croatia','كرواتيا','385'),
('HT','Haiti','هايتي','509'),
('HU','Hungary','المجر','36'),
('ID','Indonesia','إندونيسيا','62'),
('IM','Isle of Man','جزيرة مان','44'),
('IN','India','الهند','91'),
('IO','British Indian Ocean Territory','إقليم المحيط الهندي البريطاني','246'),
('IE','Ireland','أيرلندا','353'),
('IR','Iran','إيران','98'),
('IQ','Iraq','العراق','964'),
('IS','Iceland','آيسلندا','354'),
('IL','Israel','إسرائيل','972'),
('IT','Italy','إيطاليا','39'),
('JM','Jamaica','جامايكا','1876'),
('JE','Jersey','جيرزي','44'),
('JO','Jordan','الأردن','962'),
('JP','Japan','اليابان','81'),
('KZ','Kazakhstan','كازاخستان','7'),
('KE','Kenya','كينيا','254'),
('KG','Kyrgyzstan','قيرغيزستان','996'),
('KH','Cambodia','كمبوديا','855'),
('KI','Kiribati','كيريباتي','686'),
('KN','Saint Kitts and Nevis','سانت كيتس ونيفيس','1869'),
('KR','South Korea','كوريا الجنوبية','82'),
('XK','Kosovo','كوسوفو','383'),
('KW','Kuwait','الكويت','965'),
('LA','Laos','لاوس','856'),
('LB','Lebanon','لبنان','961'),
('LR','Liberia','ليبيريا','231'),
('LY','Libya','ليبيا','218'),
('LC','Saint Lucia','سانت لوسيا','1758'),
('LI','Liechtenstein','ليختنشتاين','423'),
('LK','Sri Lanka','سريلانكا','94'),
('LS','Lesotho','ليسوتو','266'),
('LT','Lithuania','ليتوانيا','370'),
('LU','Luxembourg','لوكسمبورغ','352'),
('LV','Latvia','لاتفيا','371'),
('MO','Macau','ماكاو','853'),
('MF','Saint Martin','سانت مارتن','590'),
('MA','Morocco','المغرب','212'),
('MC','Monaco','موناكو','377'),
('MD','Moldova','مولدوڤا','373'),
('MG','Madagascar','مدغشقر','261'),
('MV','Maldives','المالديف','960'),
('MX','Mexico','المكسيك','52'),
('MH','Marshall Islands','جزر مارشال','692'),
('MK','North Macedonia','شمال مقدونيا','389'),
('ML','Mali','مالي','223'),
('MT','Malta','مالطا','356'),
('MM','Myanmar','ميانمار','95'),
('ME','Montenegro','الجبل الاسود','382'),
('MN','Mongolia','منغوليا','976'),
('MP','Northern Mariana Islands','جزر ماريانا الشمالية','1670'),
('MZ','Mozambique','موزمبيق','258'),
('MR','Mauritania','موريتانيا','222'),
('MS','Montserrat','مونتسرات','1664'),
('MQ','Martinique','مارتينيك','596'),
('MU','Mauritius','موريشيوس','230'),
('MW','Malawi','مالاوي','265'),
('MY','Malaysia','ماليزيا','60'),
('YT','Mayotte','مايوت','262'),
('NA','Namibia','ناميبيا','264'),
('NC','New Caledonia','كاليدونيا الجديدة','687'),
('NE','Niger','النيجر','227'),
('NF','Norfolk Island','جزيرة نورفولك','672'),
('NG','Nigeria','نيجيريا','234'),
('NI','Nicaragua','نيكاراغوا','505'),
('NU','Niue','نييوي','683'),
('NL','Netherlands','هولندا','31'),
('NO','Norway','النرويج','47'),
('NP','Nepal','نيبال','977'),
('NR','Nauru','ناورو','674'),
('NZ','New Zealand','نيوزيلندا','64'),
('OM','Oman','عمان','968'),
('PK','Pakistan','باكستان','92'),
('PA','Panama','بنما','507'),
('PN','Pitcairn Islands','جزر بيتكيرن','64'),
('PE','Peru','بيرو','51'),
('PH','Philippines','الفلبين','63'),
('PW','Palau','بالاو','680'),
('PG','Papua New Guinea','بابوا غينيا الجديدة','675'),
('PL','Poland','بولندا','48'),
('PR','Puerto Rico','بويرتوريكو','1'),
('KP','North Korea','كوريا الشمالية','850'),
('PT','Portugal','البرتغال','351'),
('PY','Paraguay','باراغواي','595'),
('PS','Palestine','فلسطين','970'),
('PF','French Polynesia','بولينزيا الفرنسية','689'),
('QA','Qatar','قطر','974'),
('RE','Réunion','لا ريونيون','262'),
('RO','Romania','رومانيا','40'),
('RU','Russia','روسيا','7'),
('RW','Rwanda','رواندا','250'),
('SA','Saudi Arabia','السعودية','966'),
('SD','Sudan','السودان','249'),
('SN','Senegal','السنغال','221'),
('SG','Singapore','سنغافورة','65'),
('GS','South Georgia','جورجيا الجنوبية','500'),
('SJ','Svalbard and Jan Mayen','سفالبارد ويان ماين','4779'),
('SB','Solomon Islands','جزر سليمان','677'),
('SL','Sierra Leone','سيراليون','232'),
('SV','El Salvador','السلفادور','503'),
('SM','San Marino','سان مارينو','378'),
('SO','Somalia','الصومال','252'),
('PM','Saint Pierre and Miquelon','سان بيير وميكلون','508'),
('RS','Serbia','صيربيا','381'),
('SS','South Sudan','جنوب السودان','211'),
('ST','São Tomé and Príncipe','ساو تومي وبرينسيب','239'),
('SR','Suriname','سورينام','597'),
('SK','Slovakia','سلوفاكيا','421'),
('SI','Slovenia','سلوفينيا','386'),
('SE','Sweden','السويد','46'),
('SZ','Eswatini','إسواتيني','268'),
('SX','Sint Maarten','سينت مارتن','1721'),
('SC','Seychelles','سيشل','248'),
('SY','Syria','سوريا','963'),
('TC','Turks and Caicos Islands','جزر توركس وكايكوس','1649'),
('TD','Chad','تشاد','235'),
('TG','Togo','توغو','228'),
('TH','Thailand','تايلند','66'),
('TJ','Tajikistan','طاجيكستان','992'),
('TK','Tokelau','توكيلاو','690'),
('TM','Turkmenistan','تركمانستان','993'),
('TL','Timor-Leste','تيمور الشرقية','670'),
('TO','Tonga','تونغا','676'),
('TT','Trinidad and Tobago','ترينيداد وتوباغو','1868'),
('TN','Tunisia','تونس','216'),
('TR','Türkiye','تركيا','90'),
('TV','Tuvalu','توفالو','688'),
('TW','Taiwan','تايوان','886'),
('TZ','Tanzania','تنزانيا','255'),
('UG','Uganda','أوغندا','256'),
('UA','Ukraine','أوكرانيا','380'),
('UM','United States Minor Outlying Islands','جزر الولايات المتحدة الصغيرة النائية','268'),
('UY','Uruguay','الأوروغواي','598'),
('US','United States','الولايات المتحدة','1'),
('UZ','Uzbekistan','أوزباكستان','998'),
('VA','Vatican City','مدينة الفاتيكان','3'),
('VC','Saint Vincent and the Grenadines','سانت فينسنت والغرينادين','1784'),
('VE','Venezuela','فنزويلا','58'),
('VG','British Virgin Islands','جزر العذراء','1284'),
('VI','United States Virgin Islands','جزر العذراء الامريكية','1340'),
('VN','Vietnam','فيتنام','84'),
('VU','Vanuatu','فانواتو','678'),
('WF','Wallis and Futuna','واليس وفوتونا','681'),
('WS','Samoa','ساموا','685'),
('YE','Yemen','اليمن','967'),
('ZA','South Africa','جنوب أفريقيا','27'),
('ZM','Zambia','زامبيا','260'),
('ZW','Zimbabwe','زيمبابوي','263')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, name_ar = EXCLUDED.name_ar, dial_code = EXCLUDED.dial_code;

CREATE TABLE IF NOT EXISTS public.column_definitions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  field_key text NOT NULL UNIQUE,
  label text NOT NULL,
  label_ar text,
  data_type text NOT NULL DEFAULT 'text',
  is_core boolean NOT NULL DEFAULT false,
  synonyms text[] NOT NULL DEFAULT '{}',
  usage_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.column_definitions TO authenticated;
GRANT ALL ON public.column_definitions TO service_role;
ALTER TABLE public.column_definitions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "admins manage column defs" ON public.column_definitions;
CREATE POLICY "admins manage column defs" ON public.column_definitions FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
DROP TRIGGER IF EXISTS column_definitions_touch ON public.column_definitions;
CREATE TRIGGER column_definitions_touch BEFORE UPDATE ON public.column_definitions
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TABLE IF NOT EXISTS public.dataset_columns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dataset_id uuid NOT NULL REFERENCES public.datasets(id) ON DELETE CASCADE,
  source_header text NOT NULL,
  field_key text NOT NULL,
  position integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (dataset_id, field_key)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.dataset_columns TO authenticated;
GRANT ALL ON public.dataset_columns TO service_role;
ALTER TABLE public.dataset_columns ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "admins manage dataset columns" ON public.dataset_columns;
CREATE POLICY "admins manage dataset columns" ON public.dataset_columns FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

CREATE TABLE IF NOT EXISTS public.saved_views (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  dataset_id uuid REFERENCES public.datasets(id) ON DELETE CASCADE,
  country_code text REFERENCES public.countries(code),
  filters jsonb NOT NULL DEFAULT '[]'::jsonb,
  fields text[] NOT NULL DEFAULT '{}',
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.saved_views TO authenticated;
GRANT ALL ON public.saved_views TO service_role;
ALTER TABLE public.saved_views ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "admins manage saved views" ON public.saved_views;
CREATE POLICY "admins manage saved views" ON public.saved_views FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
DROP TRIGGER IF EXISTS saved_views_touch ON public.saved_views;
CREATE TRIGGER saved_views_touch BEFORE UPDATE ON public.saved_views
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS scope_mode text NOT NULL DEFAULT 'all';
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS saved_view_id uuid REFERENCES public.saved_views(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS leads_extra_gin ON public.leads USING gin (extra jsonb_path_ops);

INSERT INTO public.column_definitions (field_key,label,label_ar,is_core,synonyms) VALUES
 ('full_name','Full Name','الاسم الكامل',true,ARRAY['name','full name','fullname','contact','الاسم','اسم']),
 ('first_name','First Name','الاسم الأول',true,ARRAY['first name','firstname','fname','given name','الاسم الاول']),
 ('last_name','Last Name','اسم العائلة',true,ARRAY['last name','lastname','lname','surname','family name','العائلة']),
 ('phone','Phone','رقم الهاتف',true,ARRAY['phone','mobile','tel','whatsapp','number','msisdn','هاتف','جوال','رقم']),
 ('email','Email','البريد الإلكتروني',true,ARRAY['email','mail','e-mail','ايميل','بريد']),
 ('city','City','المدينة',true,ARRAY['city','town','area','region','مدينة','منطقة']),
 ('company','Company','الشركة',true,ARRAY['company','organization','business','شركة']),
 ('job_title','Job Title','المسمى الوظيفي',true,ARRAY['title','job','position','role','وظيفة']),
 ('website','Website','الموقع',true,ARRAY['website','url','site','domain','موقع']),
 ('gender','Gender','الجنس',false,ARRAY['gender','sex','الجنس']),
 ('birthday','Birthday','تاريخ الميلاد',false,ARRAY['birthday','birth date','dob','date of birth','الميلاد']),
 ('facebook_id','Facebook ID','معرف فيسبوك',false,ARRAY['facebook id','fbid','fb id','facebook','uid']),
 ('country_name','Country','الدولة',false,ARRAY['country','nation','الدولة'])
ON CONFLICT (field_key) DO NOTHING;